<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyBaiHat" Class="MyDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\QuanLyBaiHat.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QuanLyBaiHatConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BaiHat" Member="BaiHats">
    <Type Name="BaiHat">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaBH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenBH" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>